# This is a basic workflow to help you get started with Actions

name: MR-HealthCheck

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  PR_Health_Check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm run installdeps
      - name: Lint ui
        run: npm run lint:run:ui
      - name: Lint server
        run: npm run lint:run:server
      - name: Run server tests
        run: |
          cd server
          npm run test:unit
      - name: Run ui tests
        run: |
          cd ui
          npm run test:unit
